/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alexandre.ltrgn (https://sketchfab.com/leturgea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drone-688425e1cddb4a288a12b00246a76d43
Title: Drone
*/

import  { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from '../../public/3D/drone.glb'

 const Drone = ({currentAnimation,...props}) =>{
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);
  
  animations[0].name="idle"
  animations[1].name ="walk"
  console.log(animations);
  useEffect(()=>{
      Object.values(actions).forEach((action) => action.stop());
      if(actions[currentAnimation]){
        actions[currentAnimation].play();
      }
  },[actions, currentAnimation])
  
  
  
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.41}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal1_1">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_50"
                      geometry={nodes.Object_50.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_50.skeleton}
                    />
                    <group name="drone44_44_correction">
                      <group name="drone44_44" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Drone;
